# Generated by Django 2.1.1 on 2018-09-14 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=25, null=True)),
                ('sample_type', models.CharField(max_length=25, null=True)),
                ('unit', models.CharField(max_length=25, null=True)),
                ('measurement', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_description', models.CharField(max_length=150, null=True)),
                ('latitude', models.FloatField(default=0.0, null=True)),
                ('longitude', models.FloatField(default=0.0, null=True)),
                ('altitude', models.FloatField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='site_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='co2data.SiteLocation'),
        ),
    ]
