# Generated by Django 2.1.1 on 2018-09-12 23:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('sample_type', models.CharField(max_length=25)),
                ('unit', models.CharField(max_length=25)),
                ('measurement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteDescriptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLocations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('site_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='co2data.SiteDescriptions')),
            ],
        ),
        migrations.AddField(
            model_name='samples',
            name='site_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='co2data.SiteLocations'),
        ),
    ]
